---
- name: Install PHP
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items:
    - php5-common
    - php5-cli
    - php5-fpm
    - php5-curl
    - php5-gd
    - php5-mcrypt
    - php5-mysql
    - php5-xmlrpc

- name: Start and enable php-fpm service
  service:
    name: php5-fpm
    state: started
    enabled: true

- name: Configure PHP
  template:
    src: php.ini.j2
    dest: /etc/php5/fpm/php.ini
  notify: reload php5-fpm
