---
- name: Add dotdeb key to apt
  apt_key:
    url: "{{ dotdeb_key_url }}"
    state: present

- name: Add dotdeb repo
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb http://packages.dotdeb.org jessie all"
    - "deb-src http://packages.dotdeb.org jessie all"

- name: Ensure the system can use the HTTPS transport for APT
  stat:
    path: /usr/lib/apt/methods/https
  register: apt_https_transport

- name: Install HTTPS transport for APT
  apt:
    pkg: apt-transport-https
    state: installed
    force: true
  when: not apt_https_transport.stat.exists

- name: Update system
  apt:
    upgrade: dist
    update_cache: yes

- name: Set timezone to UTC
  timezone:
    name: Etc/UTC

- name: Install basic system dependencies
  apt:
    name: "{{ item }}"
    state: present
    force: true
  with_items:
    - curl
    - git-core
    - build-essential

- name: Create group
  group:
    name: www
    state: present

- name: Create users
  user:
    name: www-data
    group: www-data
    state: present

- name: Create directory for serverchef binaries
  file:
    mode: 0755
    path: "{{ serverchef_path }}/{{ item }}"
    state: directory
  with_items:
    - vendor
    - bin
