---
- name: Add dotdeb key to apt
  apt_key:
    url: "{{ dotdeb_key_url }}"
    state: present

- name: Add dotdeb repo
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb http://packages.dotdeb.org jessie all"
    - "deb-src http://packages.dotdeb.org jessie all"

- name: Install PHP
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items:
    - php7.0-common
    - php7.0-cli
    - php7.0-fpm
    - php7.0-curl
    - php7.0-gd
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-xmlrpc

- name: Start and enable php7.0-pfm service
  service:
    name: php7.0-fpm
    state: started
    enabled: true
