---
- name: Install PHP 7.0
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items:
    - php7.0-common
    - php7.0-cli
    - php7.0-fpm
    - php7.0-curl
    - php7.0-gd
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-xmlrpc

- name: Start and enable php7.0-pfm service
  service:
    name: php7.0-fpm
    state: started
    enabled: true
