---
- name: Create website root
  file:
    path: "{{ website_location }}/{{ website }}/{{ item }}"
    owner: www
    group: www
    mode: 0755
    state: directory
  with_items:
    - htdocs
    - configs
    - database
    - logs

- name: Create directory for WordPress download
  file:
    path: "{{ wordpress_location }}"
    state: directory
    owner: www
    group: www
    mode: 0755

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: "{{ wordpress_location }}/latest.tar.gz"
    owner: www
    group: www
    mode: 0755

- name: Extract WordPress
  command: /bin/tar -xzf "{{ wordpress_location }}/latest.tar.gz" -C "{{ website_location }}/{{ website }}/htdocs" --strip-components=1

- name: Copy nginx config for WordPress site
  template:
    src: nginx-only.conf.j2
    dest: "{{ nginx_path }}/sites-available/{{ website }}"

- name: Enable WordPress site
  file:
    src: "{{ nginx_path }}/sites-available/{{ website }}"
    dest: "{{ nginx_path }}/sites-enabled/{{ website }}"
    state: link
  notify: reload nginx

