---
- name: Create website root
  file:
    path: "{{ website_location }}/{{ website }}/{{ item }}"
    owner: www-data
    group: www-data
    mode: 0755
    state: directory
  with_items:
    - htdocs
    - configs
    - database
    - logs

- name: Create directory for WordPress download
  file:
    path: "{{ website_location }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Download WordPress
  command: wp core download
          --allow-root
          --force
          --path="{{ website_location }}/{{ website }}/htdocs"
  args:
    chdir: "{{ website_location }}/{{ website }}/htdocs"

- name: Create database for WordPress install
  mysql_db:
    name: "{{ website | replace('.', '-') }}"
    state: present

- name: Create WordPress configs
  command: wp core config
          --allow-root
          --dbname="{{ website | replace('.', '-') }}"
          --dbuser=root
          --dbpass="{{ lookup('password', playbook_dir + '/passwords/mysql chars=ascii_letters') }}"
          --path="{{ website_location }}/{{ website }}/htdocs"

- name: Install WordPress
  command: wp core install
          --allow-root
          --url="{{ website }}"
          --title="{{ title | default('WordPress with ServerChef') }}"
          --admin_user=serverchef
          --admin_password="{{ lookup('password', playbook_dir + '/passwords/' + website) }}"
          --admin_email="admin@{{ website }}"
          --path="{{ website_location }}/{{ website }}/htdocs"
  args:
    chdir: "{{ website_location }}/{{ website }}/htdocs"

- name: Copy nginx config for WordPress site
  template:
    src: nginx-only.conf.j2
    dest: "{{ nginx_path }}/sites-available/{{ website }}"

- name: Enable WordPress site
  file:
    src: "{{ nginx_path }}/sites-available/{{ website }}"
    dest: "{{ nginx_path }}/sites-enabled/{{ website }}"
    state: link
  notify: reload nginx
