---
- name: Update system
  apt:
    upgrade: dist
    update_cache: yes

- name: Set timezone to UTC
  timezone:
    name: Etc/UTC

- name: Install basic system dependencies
  apt:
    name: "{{ item }}"
    state: present
    force: true
  with_items:
    - curl
    - git-core

- name: Create group
  group:
    name: www
    state: present

- name: Create users
  user:
    name: www
    group: www
    state: present
